services:
  docs:
    build: ./
    ports:
      - 8000:8000
    volumes:
      - ./ssh:/root/.ssh
      - ./allowed_users.txt:/app/allowed_users.txt
    env_file:
      - .env
    networks:
      custom_net:
        ipv4_address: 170.20.0.2
    restart: unless-stopped
  
  smee:
    build: ./smee
    env_file:
      - .env
    networks:
      custom_net:
        ipv4_address: 170.20.0.4
    restart: unless-stopped

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 170.20.0.0/16
          gateway: 170.20.0.1