site_name: SLC Tech Documentation
copyright: Copyright &copy; 2025 SLC Tech Team
repo_url: https://github.com/Clubs-Council-IIITH/services
repo_name: Clubs-Council-IIITH/services
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Clubs-Council-IIITH

theme:
  name: "material"
  features:
    - search.suggest
    - search.share
  logo: assets/logo-darkmode.svg
  icon:
    repo: fontawesome/brands/github

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_css:
  - assets/custom.css

plugins:
  - search
  - autorefs
  - macros:
      include_dir: "/app/services"

  - mkdocstrings:
        handlers:
            python:
                paths: ["/app/services"]

nav:
  - Home: index.md
  - Frontend: frontend/index.md
  - Subgraphs:
      - Clubs:
          - Home: subgraphs/clubs/index.md
          - Main: subgraphs/clubs/main.md
          - Models: subgraphs/clubs/models.md
          - Queries: subgraphs/clubs/queries.md
          - Mutations: subgraphs/clubs/mutations.md
          - Utils: subgraphs/clubs/utils.md

      - Events:
          - Home: subgraphs/events/index.md
          - Main: subgraphs/events/main.md
          - Models: subgraphs/events/models.md
          - Queries: subgraphs/events/queries.md
          - Mutations: subgraphs/events/mutations.md
          - Utils: subgraphs/events/utils.md
          - Mailing: subgraphs/events/mailing.md

      - Interfaces:
          - Home: subgraphs/interfaces/index.md
          - Main: subgraphs/interfaces/main.md
          - Models: subgraphs/interfaces/models.md
          - Queries: subgraphs/interfaces/queries.md
          - Mutations: subgraphs/interfaces/mutations.md
          - Utils: subgraphs/interfaces/utils.md
          - Mailing: subgraphs/interfaces/mailing.md

      - Members:
          - Home: subgraphs/members/index.md
          - Main: subgraphs/members/main.md
          - Models: subgraphs/members/models.md
          - Queries: subgraphs/members/queries.md
          - Mutations: subgraphs/members/mutations.md
          - Utils: subgraphs/members/utils.md

      - Users:
          - Home: subgraphs/users/index.md
          - Main: subgraphs/users/main.md
          - Models: subgraphs/users/models.md
          - Queries: subgraphs/users/queries.md
          - Mutations: subgraphs/users/mutations.md
          - Utils: subgraphs/users/utils.md

  - Apis:
      - Auth: apis/auth.md
      - "Auth Dev": apis/auth-dev.md
      - Files: apis/files.md
